### ISSUE TITLE
Feature Request: Configurable max objects

### ISSUE THREAD

**Issue by oba11** [pottava/aws-s3-proxy#17]
Great work @pottava on the tool, was a life saver when I need to proxy some s3 request.

Please is it possible to list objects more than 1000 in a path?

Thanks

**Comment by pottava** [comment]
@oba11 Could you try `GET_ALL_PAGES_IN_DIR=true` ? I think this is a solution for you.
https://github.com/pottava/aws-s3-proxy/blob/master/README.md#1-set-environment-variables
