### ISSUE TITLE
Enabling CONTENT-ENCODING yields incorrect Content-Length header

### ISSUE THREAD

**Issue by bmjc** [pottava/aws-s3-proxy#20]
When gzipping/deflating content, the body payload is properly encoded, but the Content-Length header is not updated.

The Content-Length header should be updated to reflect the length of the payload returned, while it currently contains the length of the payload before the encoding

**Comment by pottava** [comment]
@bmjc Thank you for your report. Right, I will fix it.

**Comment by pottava** [comment]
@bmjc I think I could fix this issue. Please give it a try with the latest source or `pottava/s3-proxy:2.0rc` image.
