### ISSUE TITLE
Contrary to documentation, CONTENT_ENCODING defaults to true

### ISSUE THREAD

**Issue by bmjc** [pottava/aws-s3-proxy#21]
The dockerfile sets CONTENT_ENCODING to true by default

**Comment by pottava** [comment]
@bmjc I basically agree with you. But I don't think the default behavior can be changed so easily. So I will change it on next version. Thanks for your advice!

**Comment by bmjc** [comment]
Thanks. Note that I'm not suggesting you change the default behavior, just updating the documentation so it states that the default is true when using the docker image would be fine.

Thanks a lot for your work :)
