### ISSUE TITLE
Support for HTTP Proxy for AWS SDK

### ISSUE THREAD

**Issue by alx13** [pottava/aws-s3-proxy#33]
Problem: AWS SDK HTTP client is customly constructed without `Proxy`, hence whole thing is not working behind proxy.
Solution: 
Add proxy [here](https://github.com/pottava/aws-s3-proxy/blob/master/internal/service/aws-config.go#L31)
Like:
```go
	transport := &http.Transport{
		Proxy:              http.ProxyFromEnvironment,
		MaxIdleConns:       config.Config.MaxIdleConns,
		IdleConnTimeout:    config.Config.IdleConnTimeout,
		DisableCompression: config.Config.DisableCompression,
		TLSClientConfig:    tlsCfg,
	}
```

**Comment by pottava** [comment]
@alx13 That's a great idea! Thanks, I will add the line:)
