### ISSUE TITLE
Basic Auth problem

### ISSUE THREAD

**Issue by skrypnyk-dmytro** [pottava/aws-s3-proxy#34]
Hi!
All works well except basic auth. It no ask the pass and I can access to any resource without any creds.

This is my docker-compose.yml

proxy:
 image: pottava/s3-proxy 
 ports:
  - 80:80
 env_file: .env
 environment:
  - AWS_REGION=$AWS_REGION
  - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  - AWS_S3_BUCKET=$AWS_S3_BUCKET
  - BASIC_AUTH_USER=admin
  - BASIC_AUTH_PASS=ttt
  - ACCESS_LOG=$ACCESS_LOG
  - DIRECTORY_LISTINGS=true
  - DIRECTORY_LISTINGS_FORMAT=html
  - GET_ALL_PAGES_IN_DIR=true
 container_name: proxy

Logs:

$ docker-compose up --build
Creating proxy ... done
Attaching to proxy
proxy    | 2020/01/14 09:45:43 [config] Proxy to mifprojects-english-study-video
proxy    | 2020/01/14 09:45:43 [config] AWS Region: eu-central-1
proxy    | 2020/01/14 09:45:43 [config] Basic authentication: admin
proxy    | 2020/01/14 09:45:43 [service] listening on :80
proxy    | 2020/01/14 09:45:50 [myip:33520] 0.114 200 GET /

**Comment by snahor** [comment]
It's not documented, but you need to set `HEALTHCHECK_PATH`.

@pottava why is that needed for basic auth? https://github.com/pottava/aws-s3-proxy/blob/master/internal/http/handler-wrapper.go#L32

**Comment by skrypnyk-dmytro** [comment]
Thank you @snahor now it's work as expected

**Comment by pottava** [comment]
@snahor @skrypnyk-dmytro Sorry for the inconvenience. It is my mistake. I'll fix this issue in the next patch.

**Comment by pottava** [comment]
I think it's fixed. Thank you for your patience.
