### ISSUE TITLE
SignatureDoesNotMatch error

### ISSUE THREAD

**Issue by nerdypinkbooks** [pottava/aws-s3-proxy#35]
Getting a nebulous error:
`SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.`
I am sure that I have IAM credentials for the bucket in question. Anyone else run into this issue?

**Comment by Chrislevi** [comment]
I'm hitting the same wall, can you elaborate why you closed the issue? did you find a solution? @nerdypinkbooks

**Comment by freekdegreef** [comment]
Running into this same issue connecting to a Wasabi S3 bucket. Did one of you manage to resolve this in the end?

**Comment by freekdegreef** [comment]
Ah managed to solve it myself. In my case the bucket name was formatted as `s3://bucket-name` while it should only be `bucket-name`.
