### ISSUE TITLE
Are there any gzip options?

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [pottava/aws-s3-proxy#4]
Are there any gzip options?

Is adding the gzip option possible?

**Comment by pottava** [comment]
@b6pzeusbc54tvhw5jgpyw8pwz2x6gs Sorry, not yet. But it's worth to add the future :)
I'm going to implement it in few days. Please wait a while.

**Comment by pottava** [comment]
@b6pzeusbc54tvhw5jgpyw8pwz2x6gs Sorry for being late. I've just added an environment variable `CONTENT_ENCODING` for compressing response body. Please try it :)

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
Awesome! You're not late at all, thanks!
