### ISSUE TITLE
Improvement request: Better usage of status codes

### ISSUE THREAD

**Issue by hmatland** [pottava/aws-s3-proxy#5]
I'm testing out the proxy as a simple authentication proxy to get files from S3 regardless av tool used to download.

I do not know if it matters for my specific usecase, but I'd think several users would benefit from better http status code handling.

It now seems like every "error" is returned with 500.
Instead, it would be an improvement if for example "NoSuchKey" errors were returned as 404 back to the client.

`NoSuchKey: The specified key does not exist.
	status code: 404, request id: XXXXXXXXX, host id: YyYYYYYYYYYYYYYYYYYYYYYYYYY`

I have no experience with Go, but from the [Go SDK documentation](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/) it's seems like something similar to this is the way to go: 
```
result, err := svc.AbortMultipartUpload(params)
if err != nil {
    // Cast err to awserr.Error to handle specific error codes.
    aerr, ok := err.(awserr.Error)
    if ok && aerr.Code() == <error code to check for> {
        // Specific error code handling
    }
    return err
}

fmt.Println("AbortMultipartUpload result:")
fmt.Println(result)
```

**Comment by pottava** [comment]
@hmatland Thank you for your great idea!! And I'm sorry for my late reply..
This feature might help even for me! Thanks again:)
