### ISSUE TITLE
Not able to use s3client using IAM roles for serviceaccount

### ISSUE THREAD

**Issue by xtroncode** [pottava/aws-s3-proxy#59]
We are trying to deploy this in an EKS cluster, using IAM roles for serviceaccounts, but it does not seem to be able to authenticate to s3 using that role and we get access denied errors for our requests.

**Comment by max-rocket-internet** [comment]
@xtroncode did you find a solution?

**Comment by xtroncode** [comment]
It was my mistake, I had created the role after starting the pod, hence the token was not mounted.
