### ISSUE TITLE
folders are not listed when DIRECTORY_LISTINGS=true

### ISSUE THREAD

**Issue by amgohan** [pottava/aws-s3-proxy#8]
suppose that we  have this structure in a the s3 bucket proxied by s3-proxy : 
```
├── folder1
│   ├── f11
│   └── f12
└── folder2
    ├── f21
    └── f22
```
when DIRECTORY_LISTINGS=true
I expect that `http://proxy-endpoint/` list folder1 and folder2, but it returns empty list.
however `http://proxy-endpoint/folder1/` list files inside folder1

Thanks

**Comment by pottava** [comment]
@amgohan Thanks for your quick report. It was great help :)
